### ISSUE TITLE
GitHubクライアントを使用した作業手順の作成

### ISSUE THREAD

**Issue by gyzdisk** [bio-z/Git_Exe#1]
GitHubクライアントを使用して、Gitの一連の流れを練習する。
そのための手順書を作成する。

**Comment by himetani** [comment]
確認した

**Comment by himetani** [comment]
<ul>
<li>pushはmasterブランチにしてほしい！</li>
<li>ブランチ切ってそのままpushすると、Github上に新しくブランチができるので。</li>
<li>今回、いわさきさんが新しく切った#1*** のブランチをpullするには、</li>
  $ git pull origin \#1***
  もしくは、デスクトップ版だと、ブランチを切り替えた後にsyncボタンを押す必要ある。
- ブランチ切りながらやる、Githubフローだとmasterブランチ以外のブランチを誤ってpushしてしまう危険性があるので、pull requestが重要だと今回の件で明らかになった。
  pull requestにすると、masterブランチにmergeされることになるので新しいブランチができることはないです。</li>
<li>issue番号でブランチ切るのは、別の方法を考えた方がいいと思った。
上記のコマンドラインのpullの操作を見てもらえればわかるけど、「#」が特殊文字なのでエスケープシーケンスが必要になる。あとあとめんどそうなので、少なくとも「＃」は外したがいいかも。
</li>
